apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 702401326258.dkr.ecr.us-east-1.amazonaws.com/hello-world:latest
        ports:
        - name: http-port
          containerPort: 80
