apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: "http"
      nodePort: 30000
      targetPort: 80
  selector:
    app: hello-world

